<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=windows-1252"><meta name="viewport" content="width=device-width"><title>https://bankabillion.org/dashboard/assets_files/chart.js.download</title><link rel="stylesheet" type="text/css" href="resource://content-accessible/viewsource.css"></head><body id="viewsource" class="highlight" style="tab-size: 4"><pre id="line1"><span></span><span class="doctype">&lt;!DOCTYPE html&gt;</span><span>
<span id="line2"></span></span><span>&lt;<span class="start-tag">html</span> <span class="attribute-name">style</span>="<a class="attribute-value">height:100%</a>"&gt;</span><span>
<span id="line3"></span></span><span>&lt;<span class="start-tag">head</span>&gt;</span><span>
<span id="line4"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">viewport</a>" <span class="attribute-name">content</span>="<a class="attribute-value">width=device-width, initial-scale=1, shrink-to-fit=no</a>" <span>/</span>&gt;</span><span>
<span id="line5"></span></span><span>&lt;<span class="start-tag">title</span>&gt;</span><span> 404 Not Found
<span id="line6"></span></span><span>&lt;/<span class="end-tag">title</span>&gt;</span><span></span><span>&lt;<span class="start-tag">style</span>&gt;</span><span>@media (prefers-color-scheme:dark){body{background-color:#000!important}}</span><span>&lt;/<span class="end-tag">style</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">head</span>&gt;</span><span>
<span id="line7"></span></span><span>&lt;<span class="start-tag">body</span> <span class="attribute-name">style</span>="<a class="attribute-value">color: #444; margin:0;font: normal 14px/20px Arial, Helvetica, sans-serif; height:100%; background-color: #fff;</a>"&gt;</span><span>
<span id="line8"></span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">style</span>="<a class="attribute-value">height:auto; min-height:100%; </a>"&gt;</span><span>     </span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">style</span>="<a class="attribute-value">text-align: center; width:800px; margin-left: -400px; position:absolute; top: 30%; left:50%;</a>"&gt;</span><span>
<span id="line9"></span>        </span><span>&lt;<span class="start-tag">h1</span> <span class="attribute-name">style</span>="<a class="attribute-value">margin:0; font-size:150px; line-height:150px; font-weight:bold;</a>"&gt;</span><span>404</span><span>&lt;/<span class="end-tag">h1</span>&gt;</span><span>
<span id="line10"></span></span><span>&lt;<span class="start-tag">h2</span> <span class="attribute-name">style</span>="<a class="attribute-value">margin-top:20px;font-size: 30px;</a>"&gt;</span><span>Not Found
<span id="line11"></span></span><span>&lt;/<span class="end-tag">h2</span>&gt;</span><span>
<span id="line12"></span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>The resource requested could not be found on this server!</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line13"></span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">style</span>="<a class="attribute-value">color:#f0f0f0; font-size:12px;margin:auto;padding:0px 30px 0px 30px;position:relative;clear:both;height:100px;margin-top:-101px;background-color:#474747;border-top: 1px solid rgba(0,0,0,0.15);box-shadow: 0 1px 0 rgba(255, 255, 255, 0.3) inset;</a>"&gt;</span><span>
<span id="line14"></span></span><span>&lt;<span class="start-tag">br</span>&gt;</span><span>Proudly powered by LiteSpeed Web Server</span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>Please be advised that LiteSpeed Technologies Inc. is not a web hosting company and, as such, has no control over content found on this site.</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">body</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">html</span>&gt;</span><span>
<span id="line15"></span></span></pre></body></html>